### ISSUE TITLE
如何让新人来部署这个

### ISSUE THREAD

**Issue by Huashang12** [vivishow/liangongbao#2]
您好！这个其实很nice,但是对于一些不是计算机专业人员来说还是有点难度哈

**Comment by vivishow** [comment]
感谢建议。这个其实还好，可以直接安装mitmproxy , 然后将代码下载下来就可以了。

**Comment by robinvicky** [comment]
看起来很不错，可却是不会搭建啊。python也下了，mit也装了，还是不会运行。

**Comment by yuqiang1991** [comment]
我也卡在如何运行

**Comment by liuxsdev** [comment]
> 看起来很不错，可却是不会搭建啊。python也下了，mit也装了，还是不会运行。

跟着README走就行了，手机和电脑要在同一个局域网，电脑运行脚本后，将手机wifi的代理设置为电脑的ip和端口，最后还要在手机上安装一下证书。

**Comment by robinvicky** [comment]
> > 看起来很不错，可却是不会搭建啊。python也下了，mit也装了，还是不会运行。
> 
> 跟着README走就行了，手机和电脑要在同一个局域网，电脑运行脚本后，将手机wifi的代理设置为电脑的ip和端口，最后还要在手机上安装一下证书。

能否出个简易教程啊，没有接触过python ，难度确实大啊。

**Comment by robinvicky** [comment]
> > 看起来很不错，可却是不会搭建啊。python也下了，mit也装了，还是不会运行。
> 
> 跟着README走就行了，手机和电脑要在同一个局域网，电脑运行脚本后，将手机wifi的代理设置为电脑的ip和端口，最后还要在手机上安装一下证书。

另外，这能做挑战答题不能啊？

**Comment by liuxsdev** [comment]
> > > 看起来很不错，可却是不会搭建啊。python也下了，mit也装了，还是不会运行。
> > 
> > 
> > 跟着README走就行了，手机和电脑要在同一个局域网，电脑运行脚本后，将手机wifi的代理设置为电脑的ip和端口，最后还要在手机上安装一下证书。
> 
> 能否出个简易教程啊，没有接触过python ，难度确实大啊。

不需要任何python知识，跟着输命令就行了，遇到问题再贴上来。[嘘]挑战答题也是可以的，不过目前题库量不大，遇到题库里没有的就得自己答了。练功房多练练，扩充一下题库。

**Comment by robinvicky** [comment]
> 不需要任何python知识，跟着输命令就行了，遇到问题再贴上来。[嘘]挑战答题也是可以的，不过目前题库量不大，遇到题库里没有的就得自己答了。练功房多练练，扩充一下题库。
mit运行正常了，但脚本总是错误。
![1](https://user-images.githubusercontent.com/75261272/173036427-9533f8ed-78b9-42cd-a94f-5d98259d9ed5.png)

**Comment by liuxsdev** [comment]
@robinvicky 
额，，，所有的命令是在CMD终端输入，不需要打开python。
安装好python和mitmproxy后
1. 下载仓库源码 
2. 打开CMD(或者powershell）
3. cd 到仓库源码目录下 （或者在文件管理器中打开仓库源码，shift+右键，选择在此处打开powersell窗口）
4. 输入 mitmdump -s aqy.py -p 8888 "~d h5we.lgb360.com"
5.  。。。

**Comment by robinvicky** [comment]
![微信截图_20220610182129](https://user-images.githubusercontent.com/75261272/173045634-a8232f2f-793f-46d3-8ccf-cf10698cba62.png)
感谢，可以了
@liuxsdev  ，挑战答题的地址是多少啊？

**Comment by vivishow** [comment]
视频教程已出 [点我](https://www.bilibili.com/video/BV1rY411K7VH) 关闭喽!
