### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Huashang12** [vivishow/liangongbao#6]
![image](https://user-images.githubusercontent.com/92103699/173225282-f435c1b3-b972-4f84-864b-e41966960141.png)

**Comment by Huashang12** [comment]
> ![image](https://user-images.githubusercontent.com/92103699/173225282-f435c1b3-b972-4f84-864b-e41966960141.png)

证书安装了，进入不去链工宝的链工房，打开cmd看到这个问题，请问一下这种哪一步做错了呢

**Comment by vivishow** [comment]
显示内容是正常的, 练功房是在微信公众号链工宝里的

**Comment by vivishow** [comment]
去练功房试一试
