### ISSUE TITLE
in script aqy.py: [Errno 2] No such file or directory: 'answer/answer.json'

### ISSUE THREAD

**Issue by 5000yearsandnow** [vivishow/liangongbao#7]
![1655281179981](https://user-images.githubusercontent.com/107312372/173778952-76313e94-7b5b-43ef-898a-8e135358a514.jpg)
运行之后提示缺少文件捏。。。。

**Comment by vivishow** [comment]
新建一个就可以了,已经修复,请下载最新的

**Comment by 5000yearsandnow** [comment]
感谢大佬
