### ISSUE TITLE
请问有无链工宝题库的爬虫

### ISSUE THREAD

**Issue by mazhiyuam** [vivishow/liangongbao#9]
想请教一下，怎么爬链工宝的题库和答案？

**Comment by vivishow** [comment]
目前题库就是用号来试, 把做过的题保存下来.

**Comment by mazhiyuam** [comment]
> 目前题库就是用号来试, 把做过的题保存下来.

啊，我只有一个号一天只能试6次 😓

**Comment by vivishow** [comment]
题库在这里更新的 https://github.com/vivishow/liangongbao/tree/master/answer
